services:
  app:
    image: hello-front-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    container_name: hello-front-dev