services:
  app:
    image: front-dev
    container_name: front-dev
    ports:
      - "3000:3000"
    build: 
      context: ./front-end
      dockerfile: dev.Dockerfile
    volumes:
      - ./front-end:/usr/src/app
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "3456:27017"
    volumes:
      - ./mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
  server:
    image: serverdev
    container_name: server
    ports:
      - "3333:3000"
    depends_on:
      - mongo
    volumes:
      - ./:/usr/src/app  
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      - SECRET=secret
      - PORT=3000
      - MONGODB_URI=mongodb://the_username:the_password@mongo:27017/the_database
      - TEST_MONGODB_URI=mongodb://the_username:the_password@mongo:27017/the_database